#!/bin/bash

#
# KCPTun       Startup script for the KCPTun Server
#
# chkconfig: - 90 10
#
# description: The KCPTun is a secure tunnel based On KCP with N:M Multiplexing. \
#              (https://github.com/xtaci/kcptun)
# processname: kcptun
# config: /etc/sysconfig/kcptun
# pidfile: /var/run/kcptun.pid
#

### BEGIN INIT INFO
# Provides: KCPTun
# Required-Start: $network $syslog $local_fs $remote_fs $named
# Required-Stop: $network $local_fs $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Start and stop KCPTun Server
# Description: The KCPTun is a secure tunnel based On KCP with N:M Multiplexing.
### END INIT INFO


# Author: farawayzheng <http://blog.csdn.net/farawayzheng_necas>
#
# To install:
#   Copy this file to /etc/rc.d/init.d/kcptun
#   $ chkconfig --add kcptun
#
#
# To uninstall:
#   $ chkconfig --del kcptun
#

BASE=$(basename $0)

# modify these in /etc/sysconfig/$BASE (/etc/sysconfig/kcptun)
KCPTUN=/root/kcptun/server_linux_amd64
KCPTUN_CONF=/root/kcptun/kcptun.conf
KCPTUN_PIDFILE=/var/run/$BASE.pid
KCPTUN_LOGFILE=/var/log/$BASE.log
KCPTUN_LOCKFILE=/var/lock/subsys/$BASE
KCPTUN_OPTS="-t 127.0.0.1:10000 -l :20000 --key key --crypt aes-128 --sndwnd 1024 --rcvwnd 1024 --nocomp --mode fast2"
KCPTUN_DESC="KCPTUN"

if [ -f $KCPTUN_CONF ]; then
    . $KCPTUN_CONF
fi

# Check kcptun server is present
if [ ! -x $KCPTUN ]; then
    echo "$KCPTUN not present or not executable!"
    exit 1
fi

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

start() {

    if [ -f ${KCPTUN_LOCKFILE} ]; then

        if [ -s ${KCPTUN_PIDFILE} ]; then
            echo "$BASE might be still running, stop it first!"
            killproc -p ${KCPTUN_PIDFILE} -d ${STOP_TIMEOUT} $KCPTUN
        else
            echo "$BASE was not shut down correctly!"
        fi

        rm -f ${KCPTUN_PIDFILE} ${KCPTUN_LOCKFILE}
        sleep 2
    fi

    echo -n $"Starting $BASE: "
    $KCPTUN --log ${KCPTUN_LOGFILE} $KCPTUN_OPTS &
    RETVAL=$?

    if [ "$RETVAL" = "0" ]; then
        success
        sleep 2
        ps -A o pid,cmd | grep "$KCPTUN --log ${KCPTUN_LOGFILE} $KCPTUN_OPTS" | awk '{print $1}' | head -n 1 > ${KCPTUN_PIDFILE}
    else
        failure
    fi
    echo

    [ $RETVAL = 0 ] && touch ${KCPTUN_LOCKFILE}
    return $RETVAL
}

stop() {
    echo -n $"Stopping $BASE: "
    killproc -p ${KCPTUN_PIDFILE} -d ${STOP_TIMEOUT} $KCPTUN
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${KCPTUN_PIDFILE} ${KCPTUN_LOCKFILE}
    return $RETVAL
}


case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $BASE { start | stop | restart | status }"
        RETVAL=1
        ;;
esac

exit $RETVAL
